{% set name = "pmda" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7996860bd5add62d0bcc28361cf073517d905f31f442ef06fa7961ee92c5fbe

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dask>=0.18.0
    - distributed
    - mdanalysis>=0.19.0
    - joblib
    - six

test:
  imports:
    - pmda

about:
  home: http://github.com/MDAnalysis/pmda
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Parallel Molecular Dynamics Analysis tools'
  description: |
     Ready to use analysis and buildings blocks to write parallel analysis 
     algorithms using MDAnalysis with dask. This project is alpha software 
     and not API stable. It will and should rapidly evolve to test different
     approaches to implementing parallel analysis in a seamless and intuitive 
     fashion.
  doc_url: https://www.mdanalysis.org/pmda/
  dev_url: https://github.com/MDAnalysis/pmda

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
