appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: USbFQouC14rkdxiOgosTpGOu4NWXDSRpPBC0WPmi/gLPRyyXXXZ69UGvyGEl4uWuWiPMTMRMZ0zm7R5Vv8M3TcI003wPp1ZHKOaQkxzUOQzM5C9fYtbcmTIz/rHIRRpAP0dxgSMYFcvcyuDjuShvBlp1MS733tq0tVxgVpF7RjyWT+maFYNqXQbEIjVdWAduCq1uvTlxO8Qv485yHK76CErL6d4LiSBviC9AH92tscW4nh+nu5IkPorHGiQEkSCmHzqnmVapZLnGw2g4BvkYJV00mcPukkd4LZeubFAZ1XAEX+JaE+uBIRr7FXctcA0JmWr2ji9Lf+C0a2c/FKtC20uSFykDCkCzPajrqpWZMKbovuA0SrxpdXF4E+4T1Pfabbad6Q2gxuV66GkFH9FgAvSnWjmODUtnRwprae02/8zq+VAoVHsJcfU4Piz9MmRHnYiuV8B3IqGSBLDbm6mq/zmDMGy4CpZDJ5ndE0N/s4hwjggWS0ahMCot3zPoLWj9f9UnCBoHiT7RuyIRJcssghs0qMbeOzv15hRrqAy62aVePEBxDrwYhJ7DXe0BkBeMV7f0WDVXFZAAiuBoU+dFBPUlkZJdVRS+qBrPmmRMnKU4oqGtfO7eaUYdW7ryJ9REcTxiFCxLOB+e6i8HXvaPacVOBWQKs35A0xTHfY7uXd0=}
